import type {Metadata} from "next";
import {CssBaseline, ThemeProvider} from "@mui/material";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import theme from "@/theme/theme";
import DrawerAppBar from "@/components/AppBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
    <body>
    <CssBaseline/>
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <DrawerAppBar>
          {children}
        </DrawerAppBar>
      </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}
